### ISSUE TITLE
loading font

### ISSUE THREAD

**Issue by navtoj** [kslambert/hacker-news-arc-boost#1]
I saw that you were loading the font as a link in the head using js. Just wondering why not use a css import?

`@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;600;700&family=Press+Start+2P&display=swap');`

**Comment by kslambert** [comment]
@navtoj I tried it but it didn't seem to be loading the fonts for me with import. I don't know if it is because of the load order? Does CSS import work for you?

**Comment by navtoj** [comment]
> @navtoj I tried it but it didn't seem to be loading the fonts for me with import. I don't know if it is because of the load order? Does CSS import work for you?

it works fine on my arc, maybe an update changed something 🤔
